name: Publish Development Image

on:
  workflow_dispatch:

concurrency:
  group: docker-dev
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build-and-publish:
    needs: [ci]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project artifacts
        uses: ./.github/actions/build-bullshark

      - name: Build and publish Docker image
        uses: ./.github/actions/docker-build-publish
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ secrets.DOCKER_USERNAME }}/bullshark:dev
          labels: |
            org.opencontainers.image.title=Bullshark
            org.opencontainers.image.description=Bullshark Server (dev)
            org.opencontainers.image.source=https://codeberg.org/The_Neckript/bullshark
            org.opencontainers.image.revision=${{ github.sha }}
